#!/usr/bin/env python3
"""Append a standardized '## Refinement Report' to each module's main README,
using data from _refined/<mod>/README.md (generated) + refine-summary.json."""
from __future__ import annotations
import json
import re
from pathlib import Path

TOOLCHEST = Path.home() / "page-agent-toolchest"
REFINED = TOOLCHEST / "_refined"
summary = json.loads((REFINED / "refine-summary.json").read_text())
summary_by_mod = {r["module"]: r for r in summary}


def grep_count(text: str, pattern: str) -> str:
    m = re.search(pattern, text)
    return m.group(1) if m else "0"


LONG_FUNC_DETAIL = {
    "00-shared": "`sync-version` bulk-update loop",
    "01-llms": "`modelPatch` (138 lines — provider-specific request fixes), `parseLLMConfig`",
    "02-page-controller": "`dom_tree/index.js` extraction engine (1745 LOC, browser-use port) — 24 long items flagged",
    "03-core": "`normalizeResponse`/`autoFixer` (101 LOC), `validateAction` (39 LOC), `fetchLlmsTxt`",
    "04-ui": "none",
    "05-page-agent": "none",
    "06-mcp": "none (6 duplication pairs between MCP tool registrations)",
    "07-extension": "`TabsController` (453 LOC), `ConfigPanel`, `cards.tsx` renderers — 19 long items",
    "08-website": "30 long items across animated UI primitives + playground components",
}

for rec in summary:
    mod = rec["module"]
    gen_readme = REFINED / mod / "README.md"
    if not gen_readme.exists():
        continue
    gen = gen_readme.read_text()

    items = grep_count(gen, r"Extracted items:\*\* (\d+)")
    raw_files = grep_count(gen, r"preserved:\*\* (\d+)")
    long_f = grep_count(gen, r"Long Functions:\*\* (\d+)")
    dup = grep_count(gen, r"Duplication Pairs:\*\* (\d+)")
    coup = grep_count(gen, r"High Coupling Items:\*\* (\d+)")
    dead = grep_count(gen, r"Potential Dead Code:\*\* (\d+)")

    syntax = "PASS" if "All blocks pass validation" in gen else "see generated README"
    score = rec.get("health_score", "?")
    cross = rec.get("cross_module_edges", 0)

    report = f"""

## Refinement Report

> Generated by the `refine` pipeline (cleansed-native). Full output in [`_refined/{mod}/`](../_refined/{mod}/).

- **Items scanned:** {items} extracted (classes / functions / components) across {raw_files} source files
- **Cleaning passes applied:** metadata & lint-directive stripping (`eslint-disable`, `@ts-ignore`), unused-import pruning (word-boundary), relative-ref → TODO sanitization
- **Syntax:** ✅ {syntax}
- **Health score:** **{score}/100**
- **Long functions:** {long_f} — {LONG_FUNC_DETAIL.get(mod, "")}
- **Duplication pairs:** {dup}
- **High-coupling items:** {coup}
- **Potential dead code:** {dead} flagged
- **Package manifest:** generated (`_refined/{mod}/package.json`)

### ⚠️ Reading the dead-code number

The dead-code detector runs **per-module** — it flags any extracted item with zero
reverse-dependencies *inside this module's item graph*. Because `page-agent` is a
monorepo where each package exports its public API for **other packages** to
consume (e.g. `01-llms` exports `LLM`, `Tool`, `parseLLMConfig` used by
`03-core`/`07-extension`), most "dead" items are actually **the module's public
API**, not dead code. Treat the dead-code count as a *cross-module consumer*
inventory, not a deletion list. Real dead code would be items unused even by
their own package.

### What's actually worth attention

- **Long functions** are the real maintainability signal — especially
  `02-page-controller`'s `dom_tree/index.js` engine (a browser-use port, 24 long
  items) and `03-core`'s `autoFixer`.
- **Duplications** in `06-mcp` (MCP tool-registration boilerplate) and
  `07-extension` (React component patterns) reflect framework idioms, not bugs.
- **Health scores** dip for the large UI modules (`07-extension` 54,
  `08-website` 58) because React components are referenced via JSX, not
  import-graph edges the analyzer tracks — this understates real cohesion.
"""
    target = TOOLCHEST / mod / "README.md"
    target.read_text()  # ensure exists
    target.write_text(target.read_text().rstrip() + report)
    print(f"  ✓ appended report → {mod}/README.md")
