class CaptureStrategy(Protocol):
    """Interface for capture strategies."""

    @property
    def name(self) -> str: ...

    @property
    def fmt(self) -> str: ...

    async def setup(self) -> None: ...

    async def teardown(self) -> None: ...

    async def capture_articles(self, articles: list[dict]) -> list[ArticleCapture]: ...
